import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// The officecli tool, delivered as a local tool file into the base server's
// config dir (ADR 0033). The base process has no access to openoffice
// packages, so the file is self-contained: it POSTs the command to the
// daemon's token-gated /internal/officecli route, which runs the real,
// draft-aware createDefaultOfficeCliTool (ADR 0008 single write path).
//
// The args schema mirrors packages/core/src/office/tool.ts's officeSchema;
// the daemon side re-validates with the authoritative zod schema.

const ARGS_JSON_SCHEMA = {
  command: {
    type: 'string',
    description:
      'officecli verb: open, close, save, view, get, query, set, add, remove, move, swap, refresh, validate, batch, dump, import, merge, create, raw, raw-set, help',
  },
  file: { type: 'string', description: 'Path to the document (merge uses template instead)' },
  path: { type: 'string', description: 'DOM path (e.g., /body/p[@paraId=00100000])' },
  path2: { type: 'string', description: 'Second DOM path (swap)' },
  selector: { type: 'string', description: 'CSS-like selector (query)' },
  mode: {
    type: 'string',
    description:
      'View mode: text, annotated, outline, stats, issues, html, svg, screenshot, pdf, forms',
  },
  parent: { type: 'string', description: 'Parent DOM path (add/import target)' },
  type: {
    type: 'string',
    description: 'Element type to add (e.g., paragraph, run, table, slide, shape)',
  },
  props: {
    type: 'object',
    description: 'Properties to set (passed as repeatable --prop key=value)',
  },
  find: { type: 'string', description: 'Find this text/pattern to replace (set)' },
  replace: { type: 'string', description: 'Replacement text for --find matches (set)' },
  from: { type: 'string', description: 'Copy from an existing element path (add)' },
  to: { type: 'string', description: 'Target parent path (move)' },
  index: { type: 'string', description: 'Insert position, 0-based (add/move)' },
  after: { type: 'string', description: 'Insert/move after the element at this path' },
  before: { type: 'string', description: 'Insert/move before the element at this path' },
  operations: { type: 'array', description: 'Batch operations (passed as --commands JSON)' },
  part: { type: 'string', description: 'Document part path (raw/raw-set, e.g., /document)' },
  xpath: { type: 'string', description: 'XPath to target elements (raw-set)' },
  action: {
    type: 'string',
    description:
      'XML action (raw-set): append, prepend, insertbefore, insertafter, replace, remove, setattr',
  },
  xml: { type: 'string', description: 'XML fragment or attr=value (raw-set)' },
  source: { type: 'string', description: 'Source CSV/TSV file to import (import)' },
  template: { type: 'string', description: 'Template file with {{key}} placeholders (merge)' },
  output: { type: 'string', description: 'Output file path (merge)' },
  data: { type: 'string', description: 'JSON data or path to .json file (merge)' },
  format: { type: 'string', description: 'Format for help (docx, xlsx, pptx)' },
  query: { type: 'string', description: 'Alias for selector (query)' },
  content: { type: 'string', description: 'Deprecated: use props instead' },
} as const;

const TOOL_FILE = `// Generated by the openoffice daemon (ADR 0033). Self-contained: the base
// server process has no access to openoffice packages. Executes officecli
// through the daemon so drafts, locks, and accept/history stay daemon-owned.
const { readFileSync } = await import('node:fs');
const { join } = await import('node:path');

// export default so the registry registers it as plain 'officecli' (not
// 'officecli_officecli' — the namespace prefix applies only to named exports).
export default {
  description:
    "Create, read, and edit Word (.docx), Excel (.xlsx), and PowerPoint (.pptx) documents. Verbs: get/query/view (read), set/add/remove/move/swap (edit), batch (multi-op), validate, dump, import, merge, create, raw/raw-set (XML fallback), open/close/save (resident lifecycle), help (capability reference). Run 'officecli help' when unsure about commands or properties.",
  args: ${JSON.stringify(ARGS_JSON_SCHEMA, null, 2)},
  async execute(args, ctx) {
    const dataDir = process.env.OPENOFFICE_DATA_DIR;
    const token = process.env.OPENCODE_SERVER_PASSWORD ?? '';
    if (!dataDir) return { output: 'error: OPENOFFICE_DATA_DIR is not set' };
    let info;
    try {
      info = JSON.parse(readFileSync(join(dataDir, 'daemon.json'), 'utf-8'));
    } catch {
      return { output: 'error: cannot reach the openoffice daemon' };
    }
    const res = await fetch('http://127.0.0.1:' + info.port + '/internal/officecli', {
      method: 'POST',
      headers: {
        'content-type': 'application/json',
        'x-openoffice-base-token': token,
      },
      body: JSON.stringify({ sessionID: ctx.sessionID, params: args }),
    });
    const result = await res.json().catch(() => ({ success: false, error: 'invalid daemon response' }));
    if (!res.ok) return { output: result.error ?? 'officecli failed with status ' + res.status };
    return { output: result.output };
  },
};
`;

/** Writes tool/officecli.ts under the given config dir; returns the file path. */
export function writeOfficeCliToolFile(configDir: string): string {
  const dir = join(configDir, 'tool');
  mkdirSync(dir, { recursive: true });
  const path = join(dir, 'officecli.ts');
  writeFileSync(path, TOOL_FILE, 'utf-8');
  return path;
}
